### ISSUE TITLE
Go can't find cc-backend package

### ISSUE THREAD

**Issue by oscarminus** [ClusterCockpit/cc-backend#18]
Hi,

ein kleiner Hinweis: Ich habe versucht, cc-backend nach den Umstrukturierungen neu zu übersetzen. Allerdings stimmt die Doku nicht mit der Wirklichkeit überein:

[root@srv-o2e-403-36 cc-backend]# ls
api  cmd  config.json  configs  go.mod  go.sum  gqlgen.yml  init  internal  LICENSE  pkg  README.md  startDemo.sh  test  tools  var  web
[root@srv-o2e-403-36 cc-backend]# go get
go get: no package in current directory
[root@srv-o2e-403-36 cc-backend]# go build cmd/cc-backend/
package cmd/cc-backend is not in GOROOT (/usr/lib/golang/src/cmd/cc-backend)

Ein "go build cmd/cc-backend/main.go" hingegen funktioniert. 

Viele Grüße
Michael

**Comment by moebiusband73** [comment]
Hallo Michael,

das mit dem go get muss ich mir anschauen.
Das andere Problem mit dem bauen lag  am fehlenden ./ im README. Es muss heissen:
```
go build ./cmd/cc-backend
```

Danke für den Hinweis!
Vg Jan

**Comment by iamlouk** [comment]
Hi,

As far as I understand [this wiki entry about modules](https://github.com/golang/go/wiki/Modules) and [this issue for `golang/go/cmd/go`](https://github.com/golang/go/issues/37700), what might be confusing here is that now, after the restructuring, the root of the cc-backend repository is a go module (has a `go.mod` and a `go.sum` file), but not a go package. `go get` requires a package as an argument.

This is not really a problem though, as `go build ./cmd/cc-backend` will automatically fetch all dependencies for that package, a separate `go get` is not required (anymore, it seems to have been for older versions of go). `go get -u -d ./...` can be used to update all dependencies of all packages in the complete module/repository.

FYI: `go build cmd/cc-backend/main.go` only works because the `cmd/cc-backend` package has only one file, so it is better to use `go build ./cmd/cc-backend`.
