### ISSUE TITLE
Unable to stop failed jobs

### ISSUE THREAD

**Issue by oscarminus** [ClusterCockpit/cc-backend#29]
When i try to stop a failed job via the api, i get a 400 return code. The log file of cc-backend says:

Jul 12 08:57:02 srv-o2e-403-36.pc2.uni-paderborn.de cc-backend[750091]: [WARNING] REST API: stopTime must be larger than startTime and only running jobs can be stopped
Jul 12 08:57:02 srv-o2e-403-36.pc2.uni-paderborn.de cc-backend[750091]: [INFO]    POST /api/jobs/stop_job/ (400, 0.12kb, 0ms)

The stored data in cc-backend is:

{'id': 17268, 'jobId': 685076, 'user': '***', 'project': '***', 'cluster': '***', 'subCluster': 'main', 'partition': 'normal', 'arrayJobId': 0, 'numNodes': 1, 'numHwthreads': 55, 'numAcc': 0, 'exclusive': 0, 'monitoringStatus': 1, 'smt': 0, 'jobState': 'running', 'duration': 224153, 'walltime': 0, 'tags': [], 'resources': [{'hostname': 'n2cn0196'}], 'metaData': None, 'startTime': 1657384865}

The payload for the request is:

{'jobId': 685076, 'cluster': '***', 'stopTime': 1657384875, 'jobState': 'failed'}

The stopTime is 10 seconds after start time.

**Comment by iamlouk** [comment]
Hi, thank you for letting us know about your problems. Sadly, I cannot reproduce this one. I have some follow-up questions, feel free to send me an email if you want instead:

- Changing the state of a job that is not currently in the state "running" is prohibited on purpose. Do you want to modify the state of a previously stopped job? In that case, you will probably need a new `PATCH` REST API endpoint or so, but the `stop_job` endpoint will not be appropriate. 
- When and how did you extract the data stored in the cc-backend? I am confused because it does not look like Go `%#v` output, nor like JSON, and not like SQLite output either.
- In the stop-job payload, you do not provide the start time but you use the `jobid` (slurm, not enforced to be unique in the database) instead of the `id` (always unique, can be extracted from the `start_job` response). This means that you could theoretically be stopping the wrong job here if you have two jobs with the same slurm ID in the database (maybe because of requeuing problems mentioned in the other issue?)

If the problem has to do with multiple jobs with the same slurm ID, then you should also provide the start time in the `stop_job` payload or use the database ID. But if this is caused by a requeued job, maybe it is best to decide on a canonical solution (but I do not know slurm enough to propose one).
