### ISSUE TITLE
How to handle requeued jobs?

### ISSUE THREAD

**Issue by oscarminus** [ClusterCockpit/cc-backend#30]
I am just wondering how to handle requeued jobs. When I want to finish the job via API the message in the log is "[WARNING] REST API: invalid job state: "requeued"". This is not surprising at first, as it is also stated in the API documentation. 

However, I have the question of how to proceed with such a job. Can I simply terminate it with failed or cancled? What happens if the same slurm jobid is started again later? The job archive uses the slurm jobIds as identifier. Or should we implement an option api call to delete jobs?

**Comment by iamlouk** [comment]
Hm, we did not think about requeued jobs until now, I do not even know how they are currently handled in our local installation, maybe @moebiusband73 knows.

However, here is what you can do: The Slurm-Job-ID is not used as a unique identifier because multiple Clusters are supported. The only combination of properties that needs to be unique is `(slurm-id, cluster, start-time)`. Every job has a unique ID in the database that can also optionally be used in the REST-API.

This means that you can stop the old job (as failed or cancelled, I will look into #29 next, but that should work), and then start a new job with the same slurm-id, as long as it has a different start time. For now, there is sadly no way of marking it as "requeued".

**Comment by oscarminus** [comment]
Hi Lou, 
i have such a case now: Job 736470 got requeued because of a failure of one node. The old job has been stopped with "completed" (that should be failed in fact, seems like an error in my sync script). Then, the requeued job 736470 starts and cc-backend refuses to accept the start api call:

[WARNING] REST API: a job with that jobId, cluster and startTime already exists: dbid: 39178

I have added some DB-Exports and the Payload from the API Call as an attachmend to this post to keep it short. It seems like cc-cockpit doesn't take the start_time into account.

[payload_and_db_data.txt](https://github.com/ClusterCockpit/cc-backend/files/9100054/payload_and_db_data.txt)

**Comment by iamlouk** [comment]
So sorry again for the problems you are having, but we thank you very much for all the things you bring to our attention that we did not really think about or that were not a problem for our local installation.

As a temporary fix, you can edit [this line](https://github.com/ClusterCockpit/cc-backend/blob/cb4020ffdf51c9403a751e6406dc78cb35a159c3/internal/api/rest.go#L293) (internal/api/rest.go#L293). We apparently had problems with our own sync scripts and therefore limited the time window in which starting a job twice is allowed. Replace the `if` condition by `req.StartTime == job.StartTimeUnix` and you should have your desired behaviour.

I will suggest talking about requeued jobs at the upcoming workshop. I just asked @spacehamster87 how we are handling requeued jobs for our clusters and apparently they get new `job_id`s, but I am really not sure how that stuff works. We will think about a configuration option for this or think about a recommended way. If you have a suggestion, we would love to hear it :D.

**Comment by fodinabor** [comment]
I just also stumbled over this... lacking a better solution, would it make sense to make the 24hr delay configurable, so we don't have to use a patched cc-backend?

**Comment by moebiusband73** [comment]
Please reopen in case the problem persists
