### ISSUE TITLE
Improve visualization by allowing zoom in along the vertical axis

### ISSUE THREAD

**Issue by KParas** [ClusterCockpit/cc-backend#31]
Hi, I am a user at the FAU and have  a suggestion for improvement.

One would probably be able to gain more insight from the graphs, if it were possible to adjust the y-axis (basically zoom in) of the graph to a desired range of interest. For instance, in the attached figure, it is difficult to see how many processes have "almost zero" value and what this value is.

![job107396-flops](https://user-images.githubusercontent.com/28054097/179212249-2fdfe876-d0f8-47f5-aa89-639a39952bfc.png)

**Comment by moebiusband73** [comment]
Hi,
thanks for your notice. The source of the problem is that the plot will scale according to the reference line (the dashed line in the plot). You are right that values that are small cannot be distinguished anymore. A quick fix would be to provide a option to disable the reference line and trigger a rescaling of the values. Of course there is still the possibility that your lines are far apart and will cause the same issue then. We consider to rework the plot control UI, but this is a larger undertaking.
Another quick fix could be to sort statistics in the node table. Unfortunately at the moment if you enable core scope there you cannot sort the values anymore. Still you can see them in the table.

**Comment by moebiusband73** [comment]
Uplot does support UI handles now.

**Comment by spacehamster87** [comment]
2655bda64416431b7ce05b36553d9685ab85f21b
