### ISSUE TITLE
Improve Status View

### ISSUE THREAD

**Issue by spacehamster87** [ClusterCockpit/cc-backend#48]
Improve layout (plot arrangement and colors) and top-left statistic gauges (add units and add scaling).

**Comment by fodinabor** [comment]
I'd like to add some more improvement ideas:
We're having a cluster that's mostly used for machine learning where all jobs use the machines in a shared manner.
One can specify how many CPU cores, GPUs, and RAM a job needs. Therefore, we care way less about how many nodes are in use, but rather about how many GPUs / CPU cores / RAM are still available for a sub-cluster.

Something that I feel is more of a bug: we push our job meta-data together with the information that the jobs are using the nodes in a shared manner, but the user / project-wise list of used nodes basically lists the number of jobs as the number of used nodes. This obviously is misleading, since often jobs will run on the same node.
For us, the number of jobs or actually rather the number of GPUs used would be way more interesting.

Would be cool if CC's status view was flexible enough to allow us to present that information.

**Comment by fodinabor** [comment]
It would also be great if we could add custom metric aggregates.
One example that we'd be interested in right now is power consumption. We use cc-metric-collector to collect the IPMI values and would like to see our overall current cluster energy consumption.

**Comment by spacehamster87** [comment]
Done as of v1.2.0

* Add histogram for number of accelerators
* Add histogram for number of cores
* Change top users to Piechart
  * Selectable categories, saved by cluster
* Change top projectcs to Piechart
  * Selectable categories, saved by cluster
* Layout improvements

Open

* Custom aggregates (e.g. power consumption)
* Include memory usage (RAM)
* Extend gauges to smaller scopes

**Comment by spacehamster87** [comment]
* Re-implement roofline plots using uplot, see #211
* Optimizations in Job-View and Polarplot
